<?php // VIEW - imposition/index.php ?>

<style>
	a, button, .btn {
		border-radius: 0px;

	}
	.btn.active.focus, .btn.active:focus, .btn.focus, .btn.focus:active, .btn:active:focus, .btn:focus {
		outline:none;
	}
	.table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
    	white-space: nowrap;
	}	
	.nav-tabs li.active a, .nav-tabs li.active  a:focus, .nav-tabs  li.active a:hover {
		border-top:3px solid #337ab7;
		font-weight:bold;
		color:#555;
		border-radius:0px;

	}
	a:focus{
		outline:none;
	}  
	a.js-choice { 
		text-align:left;
	}
	a.js-choice .caret { 
		float:right;
		margin-top:10px;
	}
	.btn-blue, .btn-blue:focus, .btn-blue:active {
		background: #337ab7;
		color: white;
		outline:none;
	}
	.btn-blue:hover {
		background: #286090;
		color:white;
	}
	.btn-blue-dark, .btn-blue-dark:focus, .btn-blue-dark:active {
		background: rgb(40, 96, 144);
		color: white;
		outline:none;
	}
	.btn-blue-dark:hover {
		background: rgb(31, 74, 112);
		color:white;
	}
	
	.btn-blue-light, .btn-blue-light:focus, .btn-blue-light:active {
		background: rgb(191, 216, 237);
		color: rgb(85, 85, 85);
		outline:none;
	}
	.btn-blue-light:hover {
		background: rgb(159, 196, 229);
		color:rgb(85, 85, 85);
	}
	.dashboard-btns a .count {
		font-size:20px;
	}
	table tr.selected {
		background: rgba(255, 0, 0, 0.1) none repeat scroll 0% 0%;
		color: brown;
		cursor: not-allowed;
	}

	.bootstrap-select .selected a {
		background: rgba(51, 122, 183,1) none repeat scroll 0 0;
    	color: rgb(255, 255, 255);
	}

	.bootstrap-select .selected a:hover {
		background: rgba(51, 122, 183,0.9) none repeat scroll 0 0;
    	color: rgb(255, 255, 255);
	}
	.js-upload-mxml {
        position: relative;
        overflow: hidden;
    }
    .js-upload-mxml input[type=file] {
        position: absolute;
        top: 0;
        right: 0;
        min-width: 100%;
        min-height: 100%;
        font-size: 100px;
        text-align: right;
        filter: alpha(opacity=0);
        opacity: 0;
        outline: none;
        background: white;
        cursor: inherit;
        display: block;
    }
    #job-data-table thead {
    	background: gray;
    	color: white;
    }
    #job-data-table tfoot {
    	display: table-header-group;
    	background: lightgray;
    }
    #job-data-table tfoot th, #job-data-table tfoot td {
	    border-bottom: 3px solid rgb(128, 128, 128);
	}
	#job-data-table th .filter {
		background: rgb(255, 255, 255);
	    border: medium none;
	    border-radius: 3px;
	    padding: 3px 2px;
	    color:black;
	}
	.js-toggle-sub-menu {
		position: absolute;
		margin-left:-75px;
		z-index:99;
		border-radius:0px;
		margin-top:-15px;
		padding:0 20px 5px 20px;
		font-size:30px;
	}
	.dashboard-stat::after, .dashboard-stat::before {
	    content: " ";
	    display: table;
	}
	.dashboard-stat::after {
	    clear: both;
	}
	.dashboard-stat {
	    display: block;
		font-family: "Oswald",sans-serif;
	    margin-bottom: 0px;
	    overflow: hidden;
	}
	.dashboard-stat .main {
	    border: medium none;
	    border-radius: 0;
	    display: table;
	    padding: 0;
	    width: 100%;
	}
	.dashboard-stat .main .visual {
	    display: block;
	    float: left;
	    font-size: 35px;
	    height: 60px;
	    line-height: 35px;
	    margin-bottom: 15px;
	    padding-left: 15px;
	    padding-top: 10px;
	    width: 60px;
	}

	.dashboard-stat .main .visual > i {
	    font-size: 90px;
	    line-height: 90px;
	    margin-left: -25px;
	    color: inherit;
	    opacity: 0.1;
	}
	.dashboard-stat .main .details {
	    padding-right: 15px;
	    position: absolute;
	    right: 15px;
	}
	.dashboard-stat .main .details .number {
	    font-size: 34px;
	    font-weight: 300;
	    letter-spacing: -1px;
	    line-height: 36px;
	    margin-bottom: 0;
	    padding-top: 15px;
	    text-align: right;
	}
	.dashboard-stat .main .details .desc {
	    font-size: 16px;
	    font-weight: 300;
	    letter-spacing: 0;
	    text-align: right;
	}
	.dashboard-stat .submenu {
	    font-size: 11px;
	    font-weight: 300;
	    opacity: 1;
	    padding: 6px 10px;
	    position: relative;
	    text-transform: uppercase;
	    width:100%;
	    border-width:1px 0 0;
	    text-decoration:none;
	    text-align:left;
	}
	.dashboard-stat .submenu > i {
	    margin: -10px 0 0;
	    float: right;
	    padding:0px;
	    color:inherit;
	}
	#sub-dashboard {
		display:none;
		background:rgb(191, 216, 237);
		color:rgb(85, 85, 85);
		padding:15px;    
	}
	  
 


</style>

<script>
	var s,
	Imposition = {

		settings: {
			username: '',
			subDashboard: "#sub-dashboard",
			graphModal: "#graph-modal",
			table: "",
			btn_refresh: ".js-refresh",
			btn_submenu: "a.submenu",
			btn_submenuCollapse: ".js-submenu-left-menu-wrapper",
			btn_show_graph: ".js-show-graph",
			btn_menuDropdown: ".dropdown-menu li a",
			btn_createXml: ".js-create-xml",
			btn_uploadMxml: ".js-upload-mxml :file",
			btn_ripReportUpload: ".js-rip-report-upload",
			btn_ripFileUpload: ".js-rip-file-upload",
			modal_ripUpload: "#file-upload-modal",

			container_tableData: "#job-data-table",
			submenuTemplate_same_day_jobs: '<!--<div class="js-submenu-left-menu-wrapper" style="display:none;"><a class="btn btn-primary js-toggle-sub-menu" style=""><i class="fa fa-angle-up"></i></a></div>-->'+
				'<div class="row">'+
						'<div class="col-sm-3">'+
							'<button class="btn btn-default btn-xs pull-right js-show-graph"><i class="fa fa-line-chart"></i> Graph</button>'+
							'<label>Quantities</label>'+
							'<div class="list-group">'+
								'<button class="list-group-item" type="button">Total Same Days <span class="badge pull-right">34</span></button>'+
								'<button class="list-group-item" type="button">Completed <span class="badge pull-right">25</span></button>'+
								'<button class="list-group-item" type="button">Remaining <span class="badge pull-right">9</span></button>'+
							'</div>'+
						'</div>'+
						'<div class="col-sm-3">'+
							'<label>Priority</label>'+
							'<div class="list-group">'+
								'<button type="button" class="list-group-item">A <span class="badge pull-right">34</span></button>'+
								'<button type="button" class="list-group-item">B <span class="badge pull-right">25</span></button>'+
								'<button type="button" class="list-group-item">C <span class="badge pull-right">9</span></button>'+
								'<button type="button" class="list-group-item">D <span class="badge pull-right">9</span></button>'+
							'</div>'+
						'</div>'+
						'<div class="col-sm-3">'+
							'<label>Paper Type Imposition</label>'+
							'<div class="list-group">'+
								'<button type="button" class="list-group-item">100# <span class="badge pull-right">34</span></button>'+
								'<button type="button" class="list-group-item">70# <span class="badge pull-right">25</span></button>'+
								'<button type="button" class="list-group-item">10pt <span class="badge pull-right">9</span></button>'+
							'</div>'+
						'</div>'+
						'<div class="col-sm-3">'+
							'<label>Finish</label>'+
							'<div class="list-group">'+
								'<button type="button" class="list-group-item">Gloss Aqueous <span class="badge pull-right">34</span></button>'+
								'<button type="button" class="list-group-item">Matte Aqueous <span class="badge pull-right">25</span></button>'+
								'<button type="button" class="list-group-item">UV Front Only <span class="badge pull-right">9</span></button>'+
								'<button type="button" class="list-group-item">UV Back Only <span class="badge pull-right">9</span></button>'+
								'<button type="button" class="list-group-item">UV Both Sides <span class="badge pull-right">9</span></button>'+
							'</div>'+
						'</div>'+
						
					'</div>',
			submenuTemplate_gangs_in_process: '<!--<div class="js-submenu-left-menu-wrapper" style="display:none;"><a class="btn btn-primary js-toggle-sub-menu" style=""><i class="fa fa-angle-up"></i></a></div>-->'+
				'<div class="row">'+
						'<div class="col-sm-3">'+
							'<button class="btn btn-default btn-xs pull-right js-show-graph"><i class="fa fa-line-chart"></i> Graph</button>'+
							'<label>Quantities</label>'+
							'<div class="list-group">'+
								'<button class="list-group-item" type="button">Total Same Days <span class="badge pull-right">34</span></button>'+
								'<button class="list-group-item" type="button">Completed <span class="badge pull-right">25</span></button>'+
								'<button class="list-group-item" type="button">Remaining <span class="badge pull-right">9</span></button>'+
							'</div>'+
						'</div>'+
						'<div class="col-sm-9">'+
 							'<label>Priority</label>'+
  
							'<table class="table">'+
								'<thead>'+
							    '<tr>'+
							      '<th>Gang ID</th>'+
							      '<th>User Name</th>'+
							      '<th>Time Elapsed</th>'+
							      '<th>When Started</th>'+
							      '<th># Jobs on Gang</th>'+
							      '<th>Action</th>'+
							    '</tr>'+
							    '</thead>'+
							    '<tbody>'+
							      '<tr>'+
							        '<td>fs978fsd89s69df</td>'+
							        '<td>Kevin Mims</td>'+
							        '<td>37min</td>'+
							        '<td>10:30am 5/19/16</td>'+
							        '<td>7</td>'+
							        '<td><button class="btn btn-xs btn-default">View Jobs on Gang <i class="fa fa-angle-down"></i> </button> <button class="btn btn-xs btn-default"><i class="fa fa-mail-reply"></i> Release all Jobs</button></td>'+
							      '</tr>'+
							      '<tr>'+
							        '<td>fs978fsd89s69df</td>'+
							        '<td>Kevin Mims</td>'+
							        '<td>37min</td>'+
							        '<td>10:30am 5/19/16</td>'+
							        '<td>7</td>'+
							        '<td><button class="btn btn-xs btn-default">View Jobs on Gang <i class="fa fa-angle-down"></i> </button> <button class="btn btn-xs btn-default"><i class="fa fa-mail-reply"></i> Release all Jobs</button></td>'+
							      '</tr>'+
							      '<tr>'+
							        '<td>fs978fsd89s69df</td>'+
							        '<td>Kevin Mims</td>'+
							        '<td>37min</td>'+
							        '<td>10:30am 5/19/16</td>'+
							        '<td>7</td>'+
							        '<td><button class="btn btn-xs btn-default">View Jobs on Gang <i class="fa fa-angle-down"></i> </button> <button class="btn btn-xs btn-default"><i class="fa fa-mail-reply"></i> Release all Jobs</button></td>'+
							      '</tr>'+
							    '</tbody>'+
							  '</table>'+
							'</div>'+
					'</div>',
			chart_options: {
		        title: {
		            text: 'Same Day Jobs',
		            x: -20 //center
		        },
		        xAxis: {
		            categories: ['12am', '1am', '2am', '3am', '4am', '5am', '6am', '7am', '8am', '9am', '10am', '11am',
		            				'12pm', '1pm', '2pm', '3pm', '4pm', '5pm', '6pm', '7pm', '8pm', '9pm', '10pm', '11pm' ]
		        },
		        yAxis: {
		            title: {
		                text: 'Qty'
		            },
		            plotLines: [{
		                value: 0,
		                width: 1,
		                color: '#808080'
		            }]
		        },
		        tooltip: {
		            //valueSuffix: '#'
		        },
		        legend: {
		            layout: 'horizontal',
		            align: 'bottom',
		            verticalAlign: 'bottom',
		            borderWidth: 0
		        },
		        series: [
		        	{
		            	name: 'Total',
		            	data: [	24, 25, 28, 31, 31, 31, 34, 37, 37, 44, 49, 51, 58, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63]
		        	}, {
		            	name: 'Completed',
		            	data: [	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 10, 15, 21, 28, 34, 40, 41, 52, 57, 63, 63, 63, 63, 63 ]
		        	}, {
						name: 'Remaining',
						data: [	24, 25, 28, 31, 31, 31, 34, 37, 37, 44, 48, 41, 43, 42, 35, 29, 23, 22, 11, 6, 0,0, 0, 0, 0]
		        	}
		        ]
		    } // end chart_options
		},

		init: function() {
			s = this.settings;
			s.username = 'Kevin';
			this.bindUIActions();
			this.createDataTable();
		},

		bindUIActions: function() {
			$(s.btn_refresh).on("click", function() { 
				Imposition.refreshData($(this));
			});

			$('.dashboard-stat').on("click", s.btn_submenu, function() { 
				Imposition.handleSubmenu($(this));
			});
	    	
			$(s.btn_createXml).on("click", function(){
				Imposition.createXML($(this));
			});

	    	$(s.btn_menuDropdown).on('click', function(){
	    		Imposition.handleMenuDropdown($(this));
	    	});
	    	
			$(document).on("click", s.btn_show_graph, function() { 
				$('#graph-modal').modal('show').on('shown.bs.modal', function () {
					$('#chart').highcharts(s.chart_options);
				}).on('hidden.bs.modal', function () {
					$('#chart').empty();
				});
			});

			$(s.container_tableData).on('change', 'input:checkbox', function(){
				Imposition.handleCheckBox($(this));
			});

			$(s.btn_uploadMxml).on('change', function(){
				Imposition.triggerMxmlFileSelect($(this));
			});
			
			$(s.btn_uploadMxml).on('fileselect', function(event, numFiles, fileNames) {
				Imposition.handleMxmlUpload(event, numFiles, fileNames);
			});

			$(document).on("click", s.btn_ripReportUpload, function() { 
				Imposition.showModal(s.modal_ripUpload);
			});

			$(document).on("click", s.btn_ripFileUpload, function() { 
				Imposition.showModal(s.modal_ripUpload);
			});

		},

		showModal: function(modal){
			$(modal).modal('show').on('shown.bs.modal', function () {
				$('#imposition-file-upload-name').focus()
			}).on('hidden.bs.modal', function () {
				$('#imposition-file-upload-name').empty();
			});
		},

		createDataTable: function(){
			s.table = $(s.container_tableData).DataTable({
		        "paging": false,
		        //"scrollY": "500px",
		        'columnDefs': [{
					'targets': 0,
					'searchable':false,
					'orderable':false,
					'className': 'dt-body-center',
					'render': function (data, type, full, meta){
						return '<input type="checkbox" name="id[]" value="' + $('<div/>').text(data).html() + '">';
					}
				}],
				dom: '<"toolbar">rtip',
				/*
				// add 'B' to the dom element above to show
				'buttons': [
		            {
		                text: '<i class="fa fa-plus"></i> Create XML',
		                className: 'btn btn-default js-create-xml',
		                action: function ( e, dt, node, config ) {
		                    alert( table.rows('.selected').data().length +' row(s) selected' );
		                }
		            }
		        ],
		        */
				'order': [3, 'asc'],
				"orderCellsTop": false, // use the top header row for sorting
				initComplete: function () {
		            this.api().columns().every( function () {
		                var column = this;

		                var select = $('<select class="filter"><option value=""></option></select>')
		                    .appendTo( $(column.footer()).empty() )
		                    .on( 'change', function () {
		                        var val = $.fn.dataTable.util.escapeRegex(
		                            $(this).val()
		                        );
		
		                        column
		                            .search( val ? '^'+val+'$' : '', true, false )
		                            .draw();
		                    } );
		 
		                column.data().unique().sort().each( function ( d, j ) {
		                    select.append( '<option value="'+d+'">'+d+'</option>' )
		                } );
		            } );
		        }
		    } );
		},

		refreshData: function($btn){
	  		var elem = $btn.find('i');
	  		elem.addClass('fa-spin');
			setTimeout(function(){
		        elem.removeClass('fa-spin');
			}, 2000);

		},

		handleMenuDropdown: function($e){
			$e.closest('.dropdown').find('.btn.js-choice').html(
				'<span class="caret"></span><div style="margin-right:20px">' + $e.html() + '</div>'
			);
		},

		createXML: function($e){
			alert(s.table.rows('.selected').data().length +' row(s) selected' );
			s.table.rows('.selected').remove().draw();
		},

		triggerMxmlFileSelect: function($e){
			var input = $e,
	            numFiles = input.get(0).files ? input.get(0).files.length : 1,
	            files = $e.prop("files"),
	            fileNames = $.map(files, function(val) { return val.name; });
	        input.trigger('fileselect', [numFiles, fileNames]);
		},

		handleMxmlUpload: function(event, numFiles, fileNames){
			console.log(numFiles);
			console.log(fileNames);
			$('#metrix-xml-files').val(numFiles+' files selected');
		},

		getTemplate: function(type){
			var base = 's.submenuTemplate_';
			//var type = 'same_day_jobs';
			var template = base.concat(type);
			return eval(template);
		},

		handleSubmenu: function($elem){
			var type = $elem.parent().attr('data-type');
			
			if($elem.hasClass('btn-blue-light')){
				$elem.removeClass('btn-blue-light').addClass('btn-default');
				$(s.subDashboard).slideUp('slow', function(){
					$(this).empty();
				});
			} else {
				
				if($(s.subDashboard).is(':visible')){
					$(s.btn_submenu).each(function(){
						$(this).removeClass('btn-blue-light').addClass('btn-default');
					});
					$elem.removeClass('btn-default').addClass('btn-blue-light');
					$(s.subDashboard).slideUp('slow', function(){
						$(this).empty().html(Imposition.getTemplate(type));
					}).slideDown('slow', function(){
							//$('#chart').highcharts(s.chart_options);
					});
					
				} else {
					$elem.removeClass('btn-default').addClass('btn-blue-light');
					$(s.subDashboard).empty().html(Imposition.getTemplate(type)).slideDown('slow', function(){
							//$('#chart').highcharts(s.chart_options);
					});
				}
			}
			
		}, // end, handleSubmenu()

		handleCheckBox: function($e){
			if(!$e.hasClass('js-select-all')){
			    if($e.is(":checked")) {
			        $e.parent().parent().addClass("selected").find('.user-selected').html(s.username);
			    } else {
			        if($('.js-select-all').prop('checked')) {
			        	$(this).removeProp('checked');
			        }
			        $e.parent().parent().removeClass("selected").find('.user-selected').html('');
			    }
			} else {
				var rows = s.table.rows({ 'search': 'applied' }).nodes();
			
				if($e.prop('checked')){
					$('input[type="checkbox"]', rows).each(function(){
						$(this).prop('checked', true);
				  		$(this).parent().parent().addClass('selected').find('.user-selected').html(s.username);
					});
				} else {	
					$('input[type="checkbox"]', rows).each(function(){
						$(this).removeProp('checked');
				  		$(this).parent().parent().removeClass('selected').find('.user-selected').html('');
					});
				}

			}
		}


	};




	$(document).ready(function () {
		
		Imposition.init();

		
		

		
		

		
// enable horizontal drag scroll
//--------------------------------------------------------------------------------------------
/*	
		var mouseNotInSortableElement = false,
			drag_div = document.getElementById('sorted_imposition_table'),
			space = window.innerHeight - drag_div.offsetTop ,
			elem_height = $('#sorted_imposition_table').height();

	
	
		$.fn.draggable = function(){
			var lastPosition, position, difference;
			$( $(this).selector ).on("mousedown mouseup mousemove",function(e){
				if($("#sorted_imposition_table").hasClass('no-drag')){
					//console.log('has class');
					e.preventDefault();
				} else {
					if ( e.type == "mousedown" ) { mouseNotInSortableElement = true, lastPosition = [e.clientX, e.clientY];}
					if ( e.type == "mouseup" ) { mouseNotInSortableElement = false, $(this).css("cursor", 'grab'); }
					if ( e.type == "mousemove" && mouseNotInSortableElement == true ){
						$(this).css("cursor", 'grabbing');
						position = [e.clientX, e.clientY];
						difference = [ (position[0]-lastPosition[0]), (position[1]-lastPosition[1]) ];
						$(this).scrollLeft( $(this).scrollLeft() - difference[0] );
						//$(this).scrollTop( $(this).scrollTop() - difference[1] );
						lastPosition = [e.clientX, e.clientY];
					}
				}
				//console.log('done');
			});
			$(window).on("mouseup", function(){
				mouseNotInSortableElement = false;
			});
		}

		$("#sorted_imposition_table").draggable();
*/
		
// set the height to screen height
//--------------------------------------------------------------------------------------------
		
		function resize(){
			var space = window.innerHeight - drag_div.offsetTop;
			//$(drag_div).css("min-height", space - 55);
			//$(drag_div).css("height", space - 55); 
		}
		
		var delay = (function(){
			var timer = 0;
			return function(callback, ms){
				clearTimeout (timer);
				timer = setTimeout(callback, ms);
			};
		})();

		//resize();

		$(window).resize(function() {
			delay(function(){
				// callback
				//resize();
			}, 500);
		});


	});

</script>


<section class="">
	<div style="padding-bottom:10px" class="row">
		<div style="" class="col-sm-6">
			<h2 style="margin:0px;padding-top:7px;">
				IMPOSITION <small>dashboard</small><a class="btn js-refresh" href="#"><i class="fa fa-refresh"></i></a>
			</h2>
		</div>

		<div class="col-sm-3 col-sm-offset-3">
			<div>Location</div>
			<div class="dropdown">
				<a aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" href="#" data-target="#" class="btn btn-default btn-block js-choice" id="dLabel">
					<span class="caret"></span>
					<div class="pull-right" style="letter-spacing:1px;">
						<span class="badge js-count">2</span> 
						<span class="badge js-count">12</span> 
						<span class="badge js-count">34</span>
					</div>
					<span class="js-name">Arlington Ave H</span>
				</a>

				<ul aria-labelledby="dLabel" class="dropdown-menu" style="width:100%;">
					<li>
						<a class="btn text-left">
							<div class="pull-right" style="letter-spacing:1px;">
								<span class="badge js-count">4</span> 
								<span class="badge js-count">11</span> 
								<span class="badge js-count">56</span>
							</div>
							<span class="js-name">Arlington Ave R</span>
						</a>
					</li>
					<li>
						<a class="btn text-left">
							<div class="pull-right" style="letter-spacing:1px;">
								<span class="badge js-count">2</span> 
								<span class="badge js-count">14</span> 
								<span class="badge js-count">34</span>
							</div>
							<span class="js-name">Arlington Ave H</span>
						</a>
					</li>
					<li>
						<a class="btn text-left">
							<div class="pull-right" style="letter-spacing:1px;">
								<span class="badge js-count">19</span> 
								<span class="badge js-count">123</span> 
								<span class="badge js-count">340</span>
							</div>
							<span class="js-name">Van Neyes</span>
						</a>
					</li>
					<li>
						<a class="btn text-left">
							<div class="pull-right" style="letter-spacing:1px;">
								<span class="badge js-count">21</span> 
								<span class="badge js-count">2</span> 
								<span class="badge js-count">101</span>
							</div>
							<span class="js-name">Cleveland</span>
						</a>
					</li>
					<li class="divider"></li>
					<li>
						<a class="btn text-left">
							<div class="pull-right" style="letter-spacing:1px;">
								<span class="badge js-count">2</span> 
								<span class="badge js-count">14</span> 
								<span class="badge js-count">34</span>
							</div>
							<span class="js-name">All Locations</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>


	<div class="row" style="background: rgba(51, 122, 183, 0.2); padding: 15px 0 15px 0; border-top: 5px solid rgb(51, 122, 183); margin-bottom:15px">
		<div class="dashboard-btn col-lg-2 col-md-2 col-sm-2 col-xs-4">
            <div class="dashboard-stat" data-type="same_day_jobs">
                <a class="main btn btn-default" href="#">
                  <div class="visual"><i class="fa fa-file-o"></i></div>
                  <div class="details">
                      <div class="number"> 9 </div>
                      <div class="desc"> Same Day Jobs </div>
                  </div>
				</a>
                <a class="submenu btn btn-default" href="javascript:;"> View Stats
                    <i class="fa fa-line-chart"></i>
                </a>
            </div>
        </div>
		
		<div class="dashboard-btn col-lg-2 col-md-2 col-sm-26 col-xs-4">
            <div class="dashboard-stat" data-type="approved_jobs">
                <a class="main btn btn-default" href="#">
					<div class="visual"><i class="fa fa-check"></i></div>
					<div class="details">
						<div class="number"> 65 </div>
						<div class="desc"> Approved Jobs </div>
					</div>
				</a>
                <a class="submenu btn btn-default" href="javascript:;"> View Stats
                    <i class="fa fa-line-chart"></i>
                </a>
            </div>
        </div>
  
		<div class="dashboard-btn col-lg-2 col-md-2 col-sm-2 col-xs-4">
			<div class="dashboard-stat" data-type="total_jobs">
			    <a class="main btn btn-default" href="#">
					<div class="visual"><i class="fa fa-gear"></i></div>
					<div class="details">
						<div class="number"> 124 </div>
						<div class="desc"> Total Jobs </div>
					</div>
				</a>
			    <a class="submenu btn btn-default" href="javascript:;"> View Stats
			        <i class="fa fa-line-chart"></i>
			    </a>
			</div>
		</div>
  
		<div class="dashboard-btn col-lg-2 col-md-2 col-sm-2 col-xs-4">
			<div class="dashboard-stat" data-type="gangs_in_process">
			    <a class="main btn btn-default" href="#">
					<div class="visual"><i class="fa fa-refresh"></i></div>
					<div class="details">
						<div class="number"> 3 </div>
						<div class="desc"> Gangs In Process </div>
					</div>
				</a>
			    <a class="submenu btn btn-default" href="javascript:;"> View Stats
			        <i class="fa fa-line-chart"></i>
			    </a>
			</div>
		</div>
  
		<div class="dashboard-btn col-lg-2 col-md-2 col-sm-2 col-xs-4">
			<div class="dashboard-stat" data-type="rip_errors">
			    <a class="main btn btn-default" href="#">
					<div class="visual"><i class="fa fa-exclamation-triangle"></i></div>
					<div class="details">
						<div class="number"> 0 </div>
						<div class="desc"> Rip Errors </div>
					</div>
				</a>
			    <a class="submenu btn btn-default" href="javascript:;"> View Stats
			        <i class="fa fa-line-chart"></i>
			    </a>
			</div>
		</div>
  
		<div class="dashboard-btn col-lg-2 col-md-2 col-sm-2 col-xs-4">
			<div class="dashboard-stat" data-type="gangs_created">
			    <a class="main btn btn-default" href="#">
					<div class="visual"><i class="fa fa-thumbs-o-up"></i></div>
					<div class="details">
						<div class="number"> 26 </div>
						<div class="desc"> Gangs Created </div>
					</div>
				</a>
			    <a class="submenu btn btn-default" href="javascript:;"> View Stats
			        <i class="fa fa-line-chart"></i>
			    </a>
			</div>
		</div>
		<div class="col-xs-12 ">
			<div id="sub-dashboard" style="margin-top: 15px;"></div>
		</div>
	</div>


<!--
	<div style="background: rgba(51, 122, 183, 0.2); padding: 15px 0; border-top: 5px solid rgb(51, 122, 183); margin-bottom:15px" class="row">
        <div class="col-xs-12 dashboard-btns js-impo-stats btn-group btn-group-justified">
			<a href="#" class="btn btn-default"><div class="icon">Same Day Jobs</div><div class="count">9 </div></a>
			<a href="#" class="btn btn-default"><div class="icon">Approved Jobs</div><div class="count">65 </div></a>
			<a href="#" class="btn btn-default"><div class="icon">Total Jobs</div><div class="count">124 </div></a>
      		<a href="#" class="btn btn-default"><div class="icon">Gangs In Process</div><div class="count">3 </div></a>
	        <a href="#" class="btn btn-default"><div class="icon">Rip Errors</div><div class="count">0 </div></a>
	        <a href="#" class="btn btn-default"><div class="icon">Gangs Created</div> <div class="count">26 </div></a>
        </div>
	</div>
 -->   
	

	<div class="row">
        <div class="col-xs-12">
			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active"><a data-toggle="tab" role="tab" aria-controls="data_set" href="#data_set" aria-expanded="true">Jobs</a></li>
				<li class="p" role="presentation"><a aria-expanded="false" data-toggle="tab" role="tab" aria-controls="aws_files" href="#aws_files">Ganging</a></li>
				<li class="" role="presentation"><a aria-expanded="false" data-toggle="tab" role="tab" aria-controls="xml_uploads" href="#xml_uploads">File History</a></li>
			</ul>

			 <div class="tab-content" style="margin-bottom:40px;">
			    <div id="data_set" class="tab-pane active" style="margin-top:15px;" role="tabpanel">
					<div style="" class="row">
  
						<div class="col-sm-6 col-md-4">
							<div>With selected jobs:</div>
							<!--<button class="btn btn-block" type="button" data-toggle="modal" data-target="#create-xml-modal" data-title="Create XML" style="background: lightgray">
								<i class="fa fa-plus"></i> Create XML
							</button>-->
							<div class="btn-group btn-group-justified">
								<a class="btn btn-default js-create-xml" type="button">
									<i class="fa fa-code"></i> Create XML
								</a>
								<a class="btn btn-default js-create-xml" type="button">
									<i class="fa fa-plus"></i> Add to Existing Gang
								</a>
							</div>
						</div>

						
						<div class="col-sm-6 col-md-3">
							<div>Pre-set Filters</div>
							<div class="dropdown">
								<a id="pre-set-filters" class="btn btn-default btn-block js-choice" aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" href="#" data-target="#">
									<span class="caret"></span>
									<div class="pull-right" style="letter-spacing:1px;"></div>
									<span class="js-name">Select</span>	
								</a>
								<ul aria-labelledby="pre-set-filters" class="dropdown-menu" style="width:100%;">
									<li><a class="btn text-left"><span class="badge pull-right js-count">11</span><span class="js-name">100# Text, Gloss Text</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">51</span><span class="js-name">10pt Cover, Gloss 2 Sides</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">78</span><span class="js-name">14pt Cover, Gloss 1 side</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">23</span><span class="js-name">14pt Cover, Gloss 2 side</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">43</span><span class="js-name">14pt Cover, Uncoated</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">60</span><span class="js-name">70# Text, Uncoated</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">60</span><span class="js-name">9x12 Catalog Peal &amp; Seal</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">60</span><span class="js-name">Label, Uncoated White</span></a></li>
									<li class="divider"></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">216</span><span class="js-name">All Paperg</span></a></li>
								</ul>
							</div>
						</div>

						<!--
						<div class="col-xs-3">
							<div>Paper Finish</div>
							<select class="finish-select dropup" multiple title="Select a finish" data-width="auto"  data-show-tick="false">
							    <option title="Gloss Aqueous" data-content="<span class='badge pull-right'>24</span> Gloss Aqueous">Gloss Aqueous</option>
							    <option title="Matte Aqueous" data-content="<span class='badge pull-right'>24</span>Matte Aqueous">Matte Aqueous</option>
							    <option title="UV Frontside Only" data-content="<span class='badge pull-right'>45</span>UV Frontside Only">UV Frontside Only</option>
							    <option title="UV Backside Only" data-content="<span class='badge pull-right'>56</span>UV Backside Only">UV Backside Only</option>
							    <option title="UV Both Sides" data-content="<span class='badge pull-right'>12</span>UV Both Sides">UV Both Sides</option>
							</select>
						</div>
						-->
					</div>			
  

					<div class="table-responsive" id="sorted_imposition_table" style="">
					    <div class="colvis"></div>
					    <table id="job-data-table" class="table table-hover table-condensed draggable table-bordered">
					      <thead>
					        <tr>
					          <th><input id="select_all" class="js-select-all" name="select_all" value="1" type="checkbox" /></th>
					          <th>User</th>
					          <th>Component ID</th>
					          <th>Job ID</th>
					          <th>Priority</th>
					          <th>Gang By</th>
					          <th>Due Date</th>
					          <th>Product</th>
					          <th>Paper Type</th>
					          <th>Color</th>
					          <th>Qty</th>
					          <th>Size</th>
					          <th>Total</th>
					          <th>Front Finish</th>
					          <th>Back Finish</th>
					          <th>Custom</th>
					          <th>Binding</th>
					        </tr>
					      </thead>

					      <tfoot>
					      	<tr>
					          <th></th>
					          <th>User</th>
					          <th>Component ID</th>
					          <th>Job ID</th>
					          <th>Priority</th>
					          <th>Gang By</th>
					          <th>Due Date</th>
					          <th>Product</th>
					          <th>Paper Type</th>
					          <th>Color</th>
					          <th>Qty</th>
					          <th>Size</th>
					          <th>Total</th>
					          <th>Front Finish</th>
					          <th>Back Finish</th>
					          <th>Custom</th>
					          <th>Binding</th>
					        </tr>
					      </thead>

					      <tbody>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>6n6q47m4qe</td>
					          <td>a34ty32wert2</td>
					          <td>A</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>100#</td>
					          <td>4/0</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 3.15</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>m6tdhh95wretas</td>
					          <td>a34ty32wert2</td>
					          <td>A</td>
					          <td>5/12/16</td>
					          <td>5/16/16</td>
					          <td>Postcard</td>
					          <td>100#</td>
					          <td>4/0</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 44.11</td>
					          <td>High Gloss UV Coating</td>
					          <td></td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>gbs5354bsd</td>
					          <td>unu76nrdd4</td>
					          <td>B</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>100#</td>
					          <td>4/4</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>wm699n8bes</td>
					          <td>unu76nrdd4</td>
					          <td>A</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>70#</td>
					          <td>4/0</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>n346m36ertygs</td>
					          <td>unu76nrdd4</td>
					          <td>C</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>100#</td>
					          <td>4/4</td>
					          <td>250</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>nq36aterasae</td>
					          <td>unu76nrdd4</td>
					          <td>C</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Calendar</td>
					          <td>70#</td>
					          <td>4/4</td>
					          <td>500</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 233.18</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x11.0"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>6n6q47m4qe</td>
					          <td>a34ty32wert2</td>
					          <td>C</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Postcard</td>
					          <td>70#</td>
					          <td>4/4</td>
					          <td>1000</td>
					          <td>4.0"x6.0"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>m6tdhh95wretas</td>
					          <td>a34ty32wert2</td>
					          <td>A</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Business Cards</td>
					          <td>100#</td>
					          <td>4/4</td>
					          <td>500</td>
					          <td>3.0"x2.0"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>gbs5354bsd</td>
					          <td>unu76nrdd4</td>
					          <td>B</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>100#</td>
					          <td>4/0</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>wm699n8bes</td>
					          <td>unu76nrdd4</td>
					          <td>A</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>100#</td>
					          <td>4/0</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>n346m36ertygs</td>
					          <td>unu76nrdd4</td>
					          <td>C</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>100#</td>
					          <td>4/0</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>n346m36ertygs</td>
					          <td>unu76nrdd4</td>
					          <td>C</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>100#</td>
					          <td>4/0</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>6n6q47m4qe</td>
					          <td>a34ty32wert2</td>
					          <td>A</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>100#</td>
					          <td>4/0</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>m6tdhh95wretas</td>
					          <td>a34ty32wert2</td>
					          <td>A</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>100#</td>
					          <td>4/0</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>gbs5354bsd</td>
					          <td>unu76nrdd4</td>
					          <td>B</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>100#</td>
					          <td>4/0</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>wm699n8bes</td>
					          <td>unu76nrdd4</td>
					          <td>A</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Business Cards</td>
					          <td>70#</td>
					          <td>4/4</td>
					          <td>2000</td>
					          <td>3.0"x2.0"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td></td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>n346m36ertygs</td>
					          <td>unu76nrdd4</td>
					          <td>C</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>100#</td>
					          <td>4/0</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <td></td>
					          <td class="user-selected"></td>
					          <td>nq36aterasae</td>
					          <td>unu76nrdd4</td>
					          <td>C</td>
					          <td>5/12/16</td>
					          <td>5/15/16</td>
					          <td>Brochures</td>
					          <td>100#</td>
					          <td>4/0</td>
					          <td>100</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b>Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b>Binding Side</b>: <span class="Data">Left</span>
					          	<b>Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b>Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					      </tbody>
					    </table>
					  </div>
				</div>

			    <div style="margin-top:15px;" id="aws_files" class="tab-pane" role="tabpanel">
			    	<div class="row" style="margin-top:15px;">
					    <div class="col-sm-12">
					      <div class="panel panel-default">
					        <div class="panel-heading">
					    		<div class="pull-right">
					      			<button class="btn btn-default btn-xs"><i class="fa fa-info"></i></button>
								</div>
								<i class="fa fa-wrench"></i> Gangs In Process
								<div style="width:300px;display: inline" class="input-group input-group-sm">
					                <span class="input-group-btn" style="display: inline">
					                    <span class="btn btn-primary js-upload-mxml">
					                        XML from Metrix <input type="file" multiple="">
					                    </span>
					                </span>
					                <input id="metrix-xml-files" type="text" readonly="" class="form-control" style="display: inline;width:200px;float:none">
					            </div>
							</div>

							<div class="table-responsive"> 
					        	<table id="gang-table" class="table table-hover text-sm table-condensed">
						          <thead>
						            <tr>
						              <th></th>
						              <th>Date</th>
						              <th>Time</th>
						              <th>User</th>
						              <th>Gang Id</th>
						              <th>mXML From Metrix</th>
						              <th>Rip Report Uploaded</th>
						              <th>Rip File Uploaded</th>
						              <th>Rip Passed</th>
									  <th>Status</th>
						            </tr>
						          </thead>
						          <tbody>
						            <tr>
						              <td>1</td>
						              <td>5/12/16</td>
						              <td>10:35am</td>
						              <td>Brian</td>
						              <td>235gg25gwrf456</td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						              </td>
						              <td><button class="btn btn-xs btn-success"><i class="fa fa-thumbs-o-up"></i> GANG CREATED</button></td>
						            </tr>
						            <tr>
						              <td>2</td>
						              <td>5/12/16</td>
						              <td>10:35am</td>
						              <td>Brian</td>
						              <td>235gg25gwrf456</td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-danger btn-xs"><i class="fa fa-times"></i></button>
						                <button type="button" class="btn btn-xs btn-danger js-rip-report-upload"><i class="fa fa-download"></i> Save Now</button>
						              </td>
						              <td>
						                <button class="btn btn-danger btn-xs"><i class="fa fa-times"></i></button>
						                <button type="button" class="btn btn-xs btn-danger js-rip-file-upload"><i class="fa fa-download"></i> Save Now</button>
						              </td>
						              <td>
						                <button class="btn btn-default disabled btn-xs"><i class="fa fa-history"></i> waiting</button>
						              </td>
						              <td><button class="btn btn-xs"><i class="fa fa-wrench"></i> Gang In Process</button></td>
						            </tr>
						            <tr>
						              <td>2</td>
						              <td>5/12/16</td>
						              <td>10:35am</td>
						              <td>Brian</td>
						              <td>235gg25gwrf456</td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button> 
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-danger btn-xs"><i class="fa fa-times"></i></button>
						                <button type="button" class="btn btn-xs btn-danger js-rip-report-upload"><i class="fa fa-download"></i> Save Now</button>
						              </td>
						              <td>
						                <button class="btn btn-danger btn-xs"><i class="fa fa-times"></i></button>
						                <button type="button" class="btn btn-xs btn-danger js-rip-file-upload"><i class="fa fa-download"></i> Save Now</button>
						              </td>
						              <td>
						                <button class="btn btn-default disabled btn-xs"><i class="fa fa-history"></i> waiting</button>
						                
						              </td>
						              <td><button class="btn btn-xs"><i class="fa fa-wrench"></i> Gang In Process</button></td>
						            </tr>
						            <tr>
						              <td>3</td>
						              <td>5/12/16</td>
						              <td>10:35am</td>
						              <td>Brian</td>
						              <td>235gg25gwrf456</td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button> 
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-danger"><i class="fa fa-times"></i></button>
						                
						              </td>
						              <td><button class="btn btn-xs btn-danger"><i class="fa fa-wrench"></i> Metrix Error</button></td>
						            </tr>
						            <tr>
						              <td>4</td>
						              <td>5/12/16</td>
						              <td>10:35am</td>
						              <td>Brian</td>
						              <td>235gg25gwrf456</td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button> 
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-danger"><i class="fa fa-times"></i></button>
						                
						              </td>
						              <td><button class="btn btn-xs btn-danger"><i class="fa fa-wrench"></i> Metrix Error</button></td>
						            </tr>
						          </tbody>
								</table>
							  </div>
							</div>
					    </div>
					  </div>
				</div>

			    
			    
			    <div role="tabpanel" class="tab-pane" id="xml_uploads">
				  <div style="margin-top:15px;" class="row">
				    <div class="col-sm-3">
				      <div class="panel panel-primary">
				        <div class="panel-heading">
						    <div class="pull-right">
						      <button class="btn btn-default btn-xs"><i class="fa fa-info"></i></button>
						      <button class="btn btn-default btn-xs"><i class="fa fa-plus"></i></button>
						    </div>
				   		 XML Created
				    	</div>
  
				        <table class="table table-hover text-sm table-condensed">
				          <thead>
				            <tr>
				              <th></th>
				              <th>User</th>
				              <th>Filename</th>
				            </tr>
				          </thead>
				          <tbody>
				            <tr>
				              <td>1</td>
				              <td>Brian</td>
				              <td>23AGDS23asd28j.xml</td>
				            </tr>
				            <tr>
				              <td>2</td>
				              <td>Brian</td>
				              <td>23AGDS23asd28j.xml</td>
				            </tr>
				            <tr>
				              <td>3</td>
				              <td>Brian</td>
				              <td>23AGDS23asd28j.xml</td>
				            </tr>
				          </tbody>
				        </table>
					</div>
   				 </div>
    
			    <div class="col-sm-3">
			      <div class="panel panel-default">
			        <div class="panel-heading">
						<div class="pull-right">
							<button class="btn btn-default btn-xs"><i class="fa fa-info"></i></button>
							<button class="btn btn-default btn-xs"><i class="fa fa-plus"></i></button>
						</div>
						XML From Metrix
					</div>
			  
			        <table class="table table-hover text-sm table-condensed">
			          <thead>
			            <tr>
			              <th></th>
			              <th>User</th>
			              <th>Filename</th>
			            </tr>
			          </thead>
			          <tbody>
			            <tr>
			              <td>1</td>
			              <td>Brian</td>
			              <td>23AGDS23asd28j.xml</td>
			            </tr>
			            <tr>
			              <td>2</td>
			              <td>Brian</td>
			              <td>23AGDS23asd28j.xml</td>
			            </tr>
			            <tr>
			              <td>3</td>
			              <td>Brian</td>
			              <td>23AGDS23asd28j.xml</td>
			            </tr>
			          </tbody>
			        </table>
				  </div>
			    </div>
    
			    <div class="col-sm-3">
			      <div class="panel panel-default">
			        <div class="panel-heading">
						<div class="pull-right">
							<button class="btn btn-default btn-xs"><i class="fa fa-info"></i></button>
							<button class="btn btn-default btn-xs"><i class="fa fa-plus"></i></button>
						</div>
						 Files for Rampage
					</div>
			  
			        <table class="table table-hover text-sm table-condensed">
			          <thead>
			            <tr>
			              <th></th>
			              <th>User</th>
			              <th>Filename</th>
			            </tr>
			          </thead>
			          <tbody>
			            <tr>
			              <td>1</td>
			              <td>Brian</td>
			              <td>23AGDS23asd28j.xml</td>
			            </tr>
			            <tr>
			              <td>2</td>
			              <td>Brian</td>
			              <td>23AGDS23asd28j.xml</td>
			            </tr>
			            <tr>
			              <td>3</td>
			              <td>Brian</td>
			              <td>23AGDS23asd28j.xml</td>
			            </tr>
			          </tbody>
			        </table>
				  </div>
			    </div>
    
			    <div class="col-sm-3">
			      <div class="panel panel-default">
					<div class="panel-heading">
						<div class="pull-right">
							<button class="btn btn-default btn-xs"><i class="fa fa-info"></i></button>
							<button class="btn btn-default btn-xs"><i class="fa fa-plus"></i></button>
						</div>
						Reports for Cutting 
					</div>
			  
			        <table class="table table-hover text-sm table-condensed">
			          <thead>
			            <tr>
			              <th></th>
			              <th>User</th>
			              <th>Filename</th>
			            </tr>
			          </thead>
			          <tbody>
			            <tr>
			              <td>1</td>
			              <td>Brian</td>
			              <td>23AGDS23asd28j.xml</td>
			            </tr>
			            <tr>
			              <td>2</td>
			              <td>Brian</td>
			              <td>23AGDS23asd28j.xml</td>
			            </tr>
			            <tr>
			              <td>3</td>
			              <td>Brian</td>
			              <td>23AGDS23asd28j.xml</td>
			            </tr>
			          </tbody>
			        </table>
				  </div>
			    </div>
    
    
			    </div>
			  </div>
			</div>
		</div>
	</div>	

</section> 


<div id="file-upload-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">File Upload</h4>
      </div>
      <div class="modal-body">
        <div class="">Drag file or click to upload</div>
        <input id="imposition-file-upload-name" class="form-control"/>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Upload</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="create-xml-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Create XML from selected Components</h4>
      </div>
      <div class="modal-body">
        <div class="">Here are your selected components for the XML file</div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Download</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div id="graph-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Jobs Graph</h4>
      </div>
      <div class="modal-body">
        <div id="chart"></div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
