<?php // VIEW - imposition/index.php ?>

<style>
	.btn.active.focus, .btn.active:focus, .btn.focus, .btn.focus:active, .btn:active:focus, .btn:focus {
		outline:none;
	}
	.table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
    	white-space: nowrap;
	}	
	.nav-tabs li.active a, .nav-tabs li.active  a:focus, .nav-tabs  li.active a:hover {
		border-top:3px solid #337ab7;
		font-weight:bold;
		color:#555;
		border-radius:0px;

	}
	a:focus{
		outline:none;
	}  
	a.js-choice { 
		text-align:left;
	}
	a.js-choice .caret { 
		float:right; margin-top:-10px;
	}
	.btn-blue, .btn-blue:focus, .btn-blue:active {
		background: #337ab7;
		color: white;
		outline:none;
	}
	.btn-blue:hover {
		background: #286090;
		color:white;
	}
	.dashboard-btns a .count {
		font-size:20px;
	}
	table tr.selected {
		background: rgba(255, 0, 0, 0.1) none repeat scroll 0% 0%;
		color: brown;
		cursor: not-allowed;
	}

.bootstrap-select .selected {
	background: red;
}
</style>

<script>
	$(document).ready(function () {
		$('.js-refresh').on('click', function(){
			var $elem = $(this).find('i');
			$elem.addClass('fa-spin');
			setTimeout(function(){
		        $elem.removeClass('fa-spin');
			}, 2000);	
        });
		$('.js-impo-stats.btn-group').on('click', '.btn', function() {
			$(this).removeClass('btn-default').addClass('btn-blue').siblings().removeClass('btn-blue').addClass('btn-default');
		});

		$(".dropdown-menu li a").click(function(){
			$(this).closest('.dropdown').find('.btn.js-choice').html(
				'<div style="margin-right:20px">' + $(this).html() + '</div><span class="caret"></span>');
			//$(".btn:first-child").html($(this).text()+' &amp;amp;lt;span class="caret"&amp;amp;gt;&amp;amp;lt;/span&amp;amp;gt;');
		});
		
		
		

		
// enable horizontal drag scroll
//--------------------------------------------------------------------------------------------
	
		var mouseNotInSortableElement = false,
			drag_div = document.getElementById('sorted_imposition_table'),
			space = window.innerHeight - drag_div.offsetTop ,
			elem_height = $('#sorted_imposition_table').height();

	
	
		$.fn.draggable = function(){
			var lastPosition, position, difference;
			$( $(this).selector ).on("mousedown mouseup mousemove",function(e){
				if($("#sorted_imposition_table").hasClass('no-drag')){
					//console.log('has class');
					e.preventDefault();
				} else {
					if ( e.type == "mousedown" ) { mouseNotInSortableElement = true, lastPosition = [e.clientX, e.clientY];}
					if ( e.type == "mouseup" ) { mouseNotInSortableElement = false, $(this).css("cursor", 'grab'); }
					if ( e.type == "mousemove" && mouseNotInSortableElement == true ){
						$(this).css("cursor", 'grabbing');
						position = [e.clientX, e.clientY];
						difference = [ (position[0]-lastPosition[0]), (position[1]-lastPosition[1]) ];
						$(this).scrollLeft( $(this).scrollLeft() - difference[0] );
						//$(this).scrollTop( $(this).scrollTop() - difference[1] );
						lastPosition = [e.clientX, e.clientY];
					}
				}
				//console.log('done');
			});
			$(window).on("mouseup", function(){
				mouseNotInSortableElement = false;
			});
		}

		$("#sorted_imposition_table").draggable();

		
// set the height to screen height
//--------------------------------------------------------------------------------------------
		
		function resize(){
			var space = window.innerHeight - drag_div.offsetTop;
			//$(drag_div).css("min-height", space - 55);
			//$(drag_div).css("height", space - 55); 
		}
		
		var delay = (function(){
			var timer = 0;
			return function(callback, ms){
				clearTimeout (timer);
				timer = setTimeout(callback, ms);
			};
		})();

		resize();

		$(window).resize(function() {
			delay(function(){
				// callback
				resize();
			}, 500);
		});

		
		$('#finish-select').selectpicker({
		  style: 'btn-default',
		  showIcon: false,
		  showTick: false
		});

		/*
		$('#finish-select2').multiselect({
            buttonContainer: '<div class="btn-group"/>', 
    		buttonClass : "btn btn-default",
    		
            label: function(element) {
		        var id = $(element).val();
		        console.log("id= "+id);

		        if (!id) return $(element).html();
		        var icon;
		        $('#finish-select option').each(function() {
		            if ($(this).val() == id) {
		                icon = $(this).attr('data-icon');
		                console.log(icon);
		            }
		        });                    

		        var img = '';
		        if (typeof icon != 'undefined'){
		            img = '<i class="' + icon + '"/>,/i>'
		        }

		        return img + '&nbsp;' + $(element).html();
		    },
		    templates: {
    			li: '<li><a href="#" class=""><span class="badge pull-right">23</span><label></label></a></li>'
    		},
            /*
            templates: {
                button: '<button type="button" class="multiselect dropdown-toggle" data-toggle="dropdown"></button>',
                ul: '<ul class="multiselect-container dropdown-menu"></ul>',
                filter: '<li class="multiselect-item filter"><div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span><input class="form-control multiselect-search" type="text"></div></li>',
                filterClearBtn: '<span class="input-group-btn"><button class="btn btn-default multiselect-clear-filter" type="button"><i class="glyphicon glyphicon-remove-circle"></i></button></span>',
                li: '<li><a href="javascript:void(0);"><label></label></a></li>',
                divider: '<li class="multiselect-item divider"></li>',
                liGroup: '<li class="multiselect-item group"><label class="multiselect-group"></label></li>'
            }
            */
       // });



		
		$('#file-upload-modal').on('shown.bs.modal', function () {
			$('#imposition-file-upload-name').focus()
		});


	});
</script>


<section class="">
	<div style="padding-bottom:10px" class="row">
		<div style="" class="col-sm-6">
			<h2 style="margin:0px;padding-top:7px;">
				IMPOSITION <small>dashboard</small><a class="btn js-refresh" href="#"><i class="fa fa-refresh"></i></a>
			</h2>
		</div>

		<div class="col-sm-3 col-sm-offset-3">
			<div>Location</div>
			<div class="dropdown">
				<a aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" href="#" data-target="#" class="btn btn-default btn-block js-choice" id="dLabel">
				<div style="margin-right:20px">
					<span class="badge pull-right js-count">74</span>
					<span class="js-name">Arlington Ave H</span>
				</div>
				<span class="caret"></span>
				</a>

				<ul aria-labelledby="dLabel" class="dropdown-menu" style="width:100%;">
					<li><a class="btn text-left"><span class="badge pull-right js-count">23</span><span class="js-name">Arlington Ave R</span></a></li>
					<li><a class="btn text-left"><span class="badge pull-right js-count">74</span><span class="js-name">Arlington Ave H</span></a></li>
					<li><a class="btn text-left"><span class="badge pull-right js-count">34</span><span class="js-name">Van Neyes</span></a></li>
					<li><a class="btn text-left"><span class="badge pull-right js-count">144</span><span class="js-name">Cleveland</span></a></li>
					<li class="divider"></li>
					<li><a class="btn text-left"><span class="badge pull-right js-count">285</span><span class="js-name">All Locations</span></a></li>
				</ul>
			</div>
		</div>
	</div>

	<div style="background: rgba(51, 122, 183, 0.2); padding: 15px 0; border-top: 5px solid rgb(51, 122, 183); margin-bottom:15px" class="row">
        <div class="col-xs-12 dashboard-btns js-impo-stats btn-group btn-group-justified">
			<a href="#" class="btn btn-blue"><div class="icon">Total Jobs</div><div class="count">74 </div></a>
      		<a href="#" class="btn btn-default"><div class="icon">Due Today</div><div class="count">9 </div></a>
	        <a href="#" class="btn btn-default"><div class="icon">Gangs In Process</div><div class="count">3 </div></a>
	        <a href="#" class="btn btn-default"><div class="icon">Metrix Errors</div><div class="count">0 </div></a>
	        <a href="#" class="btn btn-default"><div class="icon">Gangs Created</div> <div class="count">26 </div></a>
        </div>
	</div>
      
	

	<div class="row">
        <div class="col-xs-12">
			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active"><a data-toggle="tab" role="tab" aria-controls="data_set" href="#data_set" aria-expanded="true">Jobs</a></li>
				<li class="p" role="presentation"><a aria-expanded="false" data-toggle="tab" role="tab" aria-controls="aws_files" href="#aws_files">Ganging</a></li>
				<li class="" role="presentation"><a aria-expanded="false" data-toggle="tab" role="tab" aria-controls="xml_uploads" href="#xml_uploads">File History</a></li>
			</ul>

			 <div class="tab-content">
			    <div style="margin-top:15px;" role="tabpanel" class="tab-pane active" id="data_set">
					<div style="" class="row">
  
						<div class="col-xs-3">
							<div>With selected jobs:</div>
							<button class="btn btn-block" style="background: lightgray">
								<i class="fa fa-plus"></i> Create XML
							</button>
						</div>

						<div class="col-xs-3">
							<div>Finish</div>
							<select id="finish-select" multiple title="Select a finish">
							    <option title="Gloss Aqueous" data-content="<span class='badge pull-right'>24</span> Gloss Aqueous">Gloss Aqueous</option>
							    <option title="Matte Aqueous" data-content="<span class='badge pull-right'>24</span>Matte Aqueous">Matte Aqueous</option>
							    <option title="UV Frontside Only" data-content="<span class='badge pull-right'>45</span>UV Frontside Only">UV Frontside Only</option>
							    <option title="UV Backside Only" data-content="<span class='badge pull-right'>56</span>UV Backside Only">UV Backside Only</option>
							    <option title="UV Both Sides" data-content="<span class='badge pull-right'>12</span>UV Both Sides">UV Both Sides</option>
							</select>

<!--
							<div class="dropdown">
								<a aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" href="http://example.com" data-target="#" class="btn btn-default btn-block js-choice" id="dLabel">
									<div style="margin-right:20px">
										<span class="js-name">Select</span>
									</div>
									<span class="caret"></span>
								</a>
								<ul aria-labelledby="dLabel" class="dropdown-menu" style="width:100%;">
									<li><a class="btn text-left"><span class="badge pull-right js-count">23</span><span class="js-name">Gloss Aqueous</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">74</span><span class="js-name">Matte Aqueous</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">74</span><span class="js-name">UV Frontside Only</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">74</span><span class="js-name">UV Backside Only</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">74</span><span class="js-name">UV Both Sides</span></a></li>
									
								</ul>
							</div>
							-->
						</div>

						<div class="col-xs-3">
							<div>Paper</div>
							<div class="dropdown">
								<a aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" href="http://example.com" data-target="#" class="btn btn-default btn-block js-choice" id="dLabel">
									<div style="margin-right:20px">
										<span class="js-name">Select</span>
									</div>
									<span class="caret"></span>
								</a>
								<ul aria-labelledby="dLabel" class="dropdown-menu" style="width:100%;">
									<li><a class="btn text-left"><span class="badge pull-right js-count">11</span><span class="js-name">100# Text, Gloss Text</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">51</span><span class="js-name">10pt Cover, Gloss 2 Sides</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">78</span><span class="js-name">14pt Cover, Gloss 1 side</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">23</span><span class="js-name">14pt Cover, Gloss 2 side</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">43</span><span class="js-name">14pt Cover, Uncoated</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">60</span><span class="js-name">70# Text, Uncoated</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">60</span><span class="js-name">9x12 Catalog Peal &amp; Seal</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">60</span><span class="js-name">Label, Uncoated White</span></a></li>
									<li class="divider"></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">216</span><span class="js-name">All Paperg</span></a></li>
								</ul>
							</div>
						</div>

						<div class="col-xs-3">
							<div>Quantity</div>
							<div class="dropdown">
								<a id="dLabel" class="btn btn-default btn-block js-choice" data-target="#" href="http://example.com" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
									<div style="margin-right:20px">
										<span class="js-name">Select</span>
									</div>
									<span class="caret"></span>
								</a>

								<ul style="width:100%;" class="dropdown-menu" aria-labelledby="dLabel">
									<li><a class="btn text-left"><span class="badge pull-right js-count">23</span><span class="js-name">10 | 4 | $30.00</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">74</span><span class="js-name">250 | 6 | $461.50</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">34</span><span class="js-name">500 | 1 | $17.00</span></a></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">144</span><span class="js-name">4000 | 1 | $131.00</span></a></li>
									<li class="divider"></li>
									<li><a class="btn text-left"><span class="badge pull-right js-count">285</span><span class="js-name">All Quantity</span></a></li>
								</ul>
							</div>
						</div>
					</div>			
  
  
					<hr>

					<div class="table-responsive" id="sorted_imposition_table" style="min-height: 310px; height: 310px; cursor: grab;">
					    <table class="table table-hover table-condensed draggable table-bordered table-striped">
					      <thead>
					        <tr>
					          <th></th>
					          <th>Component ID</th>
					          <th>Job ID</th>
					          <th>Est Ship</th>
					          <th>Qty</th>
					          <th>Color</th>
					          <th>Product #</th>
					          <th>Size</th>
					          <th>Total</th>
					          <th>Front Finish</th>
					          <th>Back Finish</th>
					          <th>Custom</th>
					          <th>Binding</th>
					        </tr>
					      </thead>
					      <tbody>
					        <tr class="selected">
					          <th scope="row"><input type="checkbox" checked class="disabled"></th>
					          <td>6n6q47m4qe</td>
					          <td>a34ty32wert2</td>
					          <td>5/15/16</td>
					          <td>100</td>
					          <td>4/4</td>
					          <td>Brochures</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b class="Label">Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b class="Label">Binding Side</b>: <span class="Data">Left</span>
					          	<b class="Label">Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b class="Label">Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <th scope="row"><input type="checkbox"></th>
					          <td>m6tdhh95wretas</td>
					          <td>a34ty32wert2</td>
					          <td>5/15/16</td>
					          <td>100</td>
					          <td>4/4</td>
					          <td>Brochures</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b class="Label">Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b class="Label">Binding Side</b>: <span class="Data">Left</span>
					          	<b class="Label">Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b class="Label">Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <th scope="row"><input type="checkbox"></th>
					          <td>gbs5354bsd</td>
					          <td>unu76nrdd4</td>
					          <td>5/15/16</td>
					          <td>100</td>
					          <td>4/4</td>
					          <td>Brochures</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b class="Label">Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b class="Label">Binding Side</b>: <span class="Data">Left</span>
					          	<b class="Label">Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b class="Label">Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <th scope="row"><input type="checkbox"></th>
					          <td>wm699n8bes</td>
					          <td>unu76nrdd4</td>
					          <td>5/15/16</td>
					          <td>100</td>
					          <td>4/4</td>
					          <td>Brochures</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b class="Label">Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b class="Label">Binding Side</b>: <span class="Data">Left</span>
					          	<b class="Label">Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b class="Label">Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <th scope="row"><input type="checkbox"></th>
					          <td>n346m36ertygs</td>
					          <td>unu76nrdd4</td>
					          <td>5/15/16</td>
					          <td>100</td>
					          <td>4/4</td>
					          <td>Brochures</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b class="Label">Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b class="Label">Binding Side</b>: <span class="Data">Left</span>
					          	<b class="Label">Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b class="Label">Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <th scope="row"><input type="checkbox"></th>
					          <td>nq36aterasae</td>
					          <td>unu76nrdd4</td>
					          <td>5/15/16</td>
					          <td>100</td>
					          <td>4/4</td>
					          <td>Brochures</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td>High Gloss UV Coating</td>
					          <td>High Gloss UV Coating</td>
					          <td>no</td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span>
					          	<b class="Label">Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span>
					          	<b class="Label">Binding Side</b>: <span class="Data">Left</span>
					          	<b class="Label">Cover Stock</b>: <span class="Data">Same As Inside</span>
					          	<b class="Label">Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					      
					      </tbody> </table> </div>
				</div>

			    <div style="margin-top:15px;" id="aws_files" class="tab-pane" role="tabpanel">
			    	<div class="row" style="margin-top:15px;">
					    <div class="col-sm-12">
					      <div class="panel panel-default">
					        <div class="panel-heading">
					    		<div class="pull-right">
					      			<button class="btn btn-default btn-xs"><i class="fa fa-info"></i></button>
								</div>
								<i class="fa fa-wrench"></i> Gangs In Process
								<input type="file" class="form-control input-sm" style="width:200px;cursor:pointer;display:inline;padding:0px;border:0px;margin-left:15px;">
							</div>

							<div class="table-responsive"> 
					        	<table class="table table-hover text-sm table-condensed">
						          <thead>
						            <tr>
						              <th></th>
						              <th>Date</th>
						              <th>Time</th>
						              <th>User</th>
						              <th>Gang Id</th>
						              <th>XML From Metrix</th>
						              <th>Report Uploaded</th>
						              <th>File Uploaded</th>
						              <th>Metrix Passed</th>
									  <th>Status</th>
						            </tr>
						          </thead>
						          <tbody>
						            <tr>
						              <td>1</td>
						              <td>5/12/16</td>
						              <td>10:35am</td>
						              <td>Brian</td>
						              <td>235gg25gwrf456</td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						              </td>
						              <td><button class="btn btn-xs btn-success"><i class="fa fa-thumbs-o-up"></i> GANG CREATED</button></td>
						            </tr>
						            <tr>
						              <td>2</td>
						              <td>5/12/16</td>
						              <td>10:35am</td>
						              <td>Brian</td>
						              <td>235gg25gwrf456</td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-danger btn-xs"><i class="fa fa-times"></i></button>
						                <button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#file-upload-modal" data-title="XML Upload"><i class="fa fa-download"></i> Save Now</button>
						              </td>
						              <td>
						                <button class="btn btn-danger btn-xs"><i class="fa fa-times"></i></button>
						                <button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#file-upload-modal" data-title="XML Upload"><i class="fa fa-download"></i> Save Now</button>
						              </td>
						              <td>
						                <button class="btn btn-default disabled btn-xs"><i class="fa fa-history"></i> waiting</button>
						              </td>
						              <td><button class="btn btn-xs"><i class="fa fa-wrench"></i> Gang In Process</button></td>
						            </tr>
						            <tr>
						              <td>2</td>
						              <td>5/12/16</td>
						              <td>10:35am</td>
						              <td>Brian</td>
						              <td>235gg25gwrf456</td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button> 
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-danger btn-xs"><i class="fa fa-times"></i></button>
						                <button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#file-upload-modal" data-title="XML Upload"><i class="fa fa-download"></i> Save Now</button>
						              </td>
						              <td>
						                <button class="btn btn-danger btn-xs"><i class="fa fa-times"></i></button>
						                <button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#file-upload-modal" data-title="XML Upload"><i class="fa fa-download"></i> Save Now</button>
						              </td>
						              <td>
						                <button class="btn btn-default disabled btn-xs"><i class="fa fa-history"></i> waiting</button>
						                
						              </td>
						              <td><button class="btn btn-xs"><i class="fa fa-wrench"></i> Gang In Process</button></td>
						            </tr>
						            <tr>
						              <td>3</td>
						              <td>5/12/16</td>
						              <td>10:35am</td>
						              <td>Brian</td>
						              <td>235gg25gwrf456</td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button> 
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-danger"><i class="fa fa-times"></i></button>
						                
						              </td>
						              <td><button class="btn btn-xs btn-danger"><i class="fa fa-wrench"></i> Metrix Error</button></td>
						            </tr>
						            <tr>
						              <td>4</td>
						              <td>5/12/16</td>
						              <td>10:35am</td>
						              <td>Brian</td>
						              <td>235gg25gwrf456</td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button> 
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-default"><i class="text-success fa fa-check"></i></button>
						                <button class="btn btn-default btn-xs"><i class="fa fa-file-o"></i> View</button>
						              </td>
						              <td>
						                <button class="btn btn-xs btn-danger"><i class="fa fa-times"></i></button>
						                
						              </td>
						              <td><button class="btn btn-xs btn-danger"><i class="fa fa-wrench"></i> Metrix Error</button></td>
						            </tr>
						          </tbody>
								</table>
							  </div>
							</div>
					    </div>
					  </div>
				</div>

			    
			    
			    <div role="tabpanel" class="tab-pane" id="xml_uploads">
				  <div style="margin-top:15px;" class="row">
				    <div class="col-sm-3">
				      <div class="panel panel-primary">
				        <div class="panel-heading">
						    <div class="pull-right">
						      <button class="btn btn-default btn-xs"><i class="fa fa-info"></i></button>
						      <button class="btn btn-default btn-xs"><i class="fa fa-plus"></i></button>
						    </div>
				   		 XML Created
				    	</div>
  
				        <table class="table table-hover text-sm table-condensed">
				          <thead>
				            <tr>
				              <th></th>
				              <th>User</th>
				              <th>Filename</th>
				            </tr>
				          </thead>
				          <tbody>
				            <tr>
				              <td>1</td>
				              <td>Brian</td>
				              <td>23AGDS23asd28j.xml</td>
				            </tr>
				            <tr>
				              <td>2</td>
				              <td>Brian</td>
				              <td>23AGDS23asd28j.xml</td>
				            </tr>
				            <tr>
				              <td>3</td>
				              <td>Brian</td>
				              <td>23AGDS23asd28j.xml</td>
				            </tr>
				          </tbody>
				        </table>
					</div>
   				 </div>
    
    <div class="col-sm-3">
      <div class="panel panel-default">
        <div class="panel-heading">
    <div class="pull-right">
      <button class="btn btn-default btn-xs"><i class="fa fa-info"></i></button>
      <button class="btn btn-default btn-xs"><i class="fa fa-plus"></i></button>
    </div>
    XML Uploaded</div>
  
        <table class="table table-hover text-sm table-condensed">
          <thead>
            <tr>
              <th></th>
              <th>User</th>
              <th>Filename</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Brian</td>
              <td>23AGDS23asd28j.xml</td>
            </tr>
            <tr>
              <td>2</td>
              <td>Brian</td>
              <td>23AGDS23asd28j.xml</td>
            </tr>
            <tr>
              <td>3</td>
              <td>Brian</td>
              <td>23AGDS23asd28j.xml</td>
            </tr>
          </tbody>
        </table>
</div>
    </div>
    
    <div class="col-sm-3">
      <div class="panel panel-default">
        <div class="panel-heading">
    <div class="pull-right">
      <button class="btn btn-default btn-xs"><i class="fa fa-info"></i></button>
      <button class="btn btn-default btn-xs"><i class="fa fa-plus"></i></button>
    </div>
    Files Uploaded</div>
  
        <table class="table table-hover text-sm table-condensed">
          <thead>
            <tr>
              <th></th>
              <th>User</th>
              <th>Filename</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Brian</td>
              <td>23AGDS23asd28j.xml</td>
            </tr>
            <tr>
              <td>2</td>
              <td>Brian</td>
              <td>23AGDS23asd28j.xml</td>
            </tr>
            <tr>
              <td>3</td>
              <td>Brian</td>
              <td>23AGDS23asd28j.xml</td>
            </tr>
          </tbody>
        </table>
</div>
    </div>
    
    <div class="col-sm-3">
      <div class="panel panel-default">
        <div class="panel-heading">
    <div class="pull-right">
      <button class="btn btn-default btn-xs"><i class="fa fa-info"></i></button>
      <button class="btn btn-default btn-xs"><i class="fa fa-plus"></i></button>
    </div>
    Reports Uploaded</div>
  
        <table class="table table-hover text-sm table-condensed">
          <thead>
            <tr>
              <th></th>
              <th>User</th>
              <th>Filename</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Brian</td>
              <td>23AGDS23asd28j.xml</td>
            </tr>
            <tr>
              <td>2</td>
              <td>Brian</td>
              <td>23AGDS23asd28j.xml</td>
            </tr>
            <tr>
              <td>3</td>
              <td>Brian</td>
              <td>23AGDS23asd28j.xml</td>
            </tr>
          </tbody>
        </table>
</div>
    </div>
    
    
			    </div></div>
			</div>
		</div>
	</div>	

</section> 


<div id="file-upload-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">File Upload</h4>
      </div>
      <div class="modal-body">
        <div class="">Drag file or click to upload</div>
        <input id="imposition-file-upload-name" class="form-control"/>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Upload</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
