<?php // VIEW - imposition/index.php ?>

<style>
  .nav-tabs li.active a, .nav-tabs li.active  a:focus, .nav-tabs  li.active a:hover {
    border-top:3px solid #337ab7;
    font-weight:bold;
    color:#555;
    border-radius:0px;
    
  }
  a:focus{outline:none; }  
</style>

<script>
	$(document).ready(function () {
		$(".dropdown-menu li a").click(function(){
			console.log($(this).parent().parent());
			console.log($(this).text());
			$(this).parent().parent().closest(".btn").html($(this).text()+' <span class="caret"></span>');
			//$(".btn:first-child").html($(this).text()+' <span class="caret"></span>');
		});
	});
</script>


<section class="">
	<div class="row" style="margin-bottom:15px">
		<div class="col-sm-6" style="">
			<h2 style="margin:0px;padding-top:7px;border-bottom:5px solid #337ab7;background:#faf5f;">IMPOSITION <small>dashboard</small><a href="#" class="btn"><i class="fa fa-refresh"></i></a></h2>
		</div>

		<div class="col-sm-6 text-right">
			<a class="btn btn-lg btn-default" href="#"><i class="glyphicon glyphicon-download"></i> Download XML</a>
			<a class="btn btn-lg btn-default" href="#"><i class="fa fa-upload"></i> Upload XML</a>
			<a class="btn btn-lg btn-default" href="#"><i class="fa fa-upload"></i> Upload File</a>
			<a class="btn btn-lg btn-default" href="#"><i class="fa fa-upload"></i> Upload PDF</a>
		</div>
	</div>

	<div class="row">
        <div class="col-xs-12 dBtnWrapper btn-group btn-group-justified">
			<a class="btn btn-default" href="#"><div class="icon">Total Jobs</div><div class="count">74 </div></a>
      		<a class="btn btn-default" href="#"><div class="icon">Due Today</div><div class="count">9 </div></a>
	        <a class="btn btn-default" href="#"><div class="icon">Gangs In Process</div><div class="count">3 </div></a>
	        <a class="btn btn-default" href="#"><div class="icon">Metrix Errors</div><div class="count">0 </div></a>
	        <a class="btn btn-default" href="#"><div class="icon">Gangs Created</div> <div class="count">26 </div></a>
        </div>
	</div>
      
	<div style="margin-bottom:15px; margin-top:5px;padding:15px 0px 25px" class="row">
		<div class="col-sm-9">
			<div class="row">
				<div class="col-xs-3">
					<div>Location</div>
					<div class="dropdown">
						<a id="dLabel" class="btn btn-default btn-block" data-target="#" href="http://example.com" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> None <span class="caret"></span>
						</a>

						<ul style="width:100%;" class="dropdown-menu" aria-labelledby="dLabel">
							<li><a class="btn text-left"><span class="badge pull-right">23</span> Arlington Ave R</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">74</span> Arlington Ave H</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">34</span> Van Neyes</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">144</span> Cleveland</a></li>
							<li class="divider"></li>
							<li><a class="btn text-left"><span class="badge pull-right">285</span> All</a></li>
						</ul>
					</div>
	            </div>

				<div class="col-xs-3">
					<div>Finish</div>
					<div class="dropdown">
						<a id="dLabel" class="btn btn-default btn-block" data-target="#" href="http://example.com" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> None  <span class="caret"></span></a>
						<ul style="width:100%;" class="dropdown-menu" aria-labelledby="dLabel">
							<li><a class="btn text-left"><span class="badge pull-right">23</span> Gloss Aqueous</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">74</span> Matte Aqueous</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">74</span> Uncoated</a></li>
							<li class="divider"></li>
							<li><a class="btn text-left"><span class="badge pull-right">97</span> All</a></li>
						</ul>
					</div>
				</div>

				<div class="col-xs-3">
					<div>Paper</div>
					<div class="dropdown">
						<a id="dLabel" class="btn btn-default btn-block" data-target="#" href="http://example.com" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">None <span class="caret"></span></a>
						<ul style="width:100%;" class="dropdown-menu" aria-labelledby="dLabel">
							<li><a class="btn text-left"><span class="badge pull-right">11</span> 100# Text, Gloss Text</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">51</span> 10pt Cover, Gloss 2 Sides</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">78</span> 14pt Cover, Gloss 1 side</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">23</span> 14pt Cover, Gloss 2 side</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">43</span> 14pt Cover, Uncoated</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">60</span> 70# Text, Uncoated</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">60</span> 9x12 Catalog Peal & Seal</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">60</span> Label, Uncoated White</a></li>
							<li class="divider"></li>
							<li><a class="btn text-left"><span class="badge pull-right">216</span> All</a></li>
						</ul>
					</div>
				</div>

				<div class="col-xs-3">
					<div>Quantity</div>
					<div class="dropdown">
						<a id="dLabel" class="btn btn-default btn-block" data-target="#" href="http://example.com" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> None <span class="caret"></span>
						</a>

						<ul style="width:100%;" class="dropdown-menu" aria-labelledby="dLabel">
							<li><a class="btn text-left"><span class="badge pull-right">23</span> 10 | 4 | $30.00</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">74</span> 250 | 6 | $461.50</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">34</span> 500 | 1 | $17.00</a></li>
							<li><a class="btn text-left"><span class="badge pull-right">144</span> 4000 | 1 | $131.00</a></li>
							<li class="divider"></li>
							<li><a class="btn text-left"><span class="badge pull-right">285</span> All</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>

		<div class="col-xs-3">
			<div>Due Date <span style="color:red;">*</span></div>
			<div class="dropdown ">
				<a id="dLabel" class="btn btn-default btn-block" data-target="#" href="http://example.com" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> None <span class="caret"></span></a>

				<ul style="width:100%;" class="dropdown-menu" aria-labelledby="dLabel">
					<li><a class="btn text-left"><span class="badge pull-right">12</span> 5/13/16</a></li>
					<li><a class="btn text-left"><span class="badge pull-right">41</span> 5/14/16</a></li>
					<li><a class="btn text-left"><span class="badge pull-right">38</span> 5/15/16</a></li>
					<li><a class="btn text-left"><span class="badge pull-right">17</span> 5/16/16</a></li>
					<li class="divider"></li>
					<li><a class="btn text-left"><span class="badge pull-right">97</span> All</a></li>
				</ul>
			</div>
		</div>
	</div>

	<div class="row">
        <div class="col-xs-12">
			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active"><a aria-expanded="true" href="#data_set" aria-controls="data_set" role="tab" data-toggle="tab">Data Set</a></li>
				<li class="" role="presentation"><a href="#xml_uploads" aria-controls="xml_uploads" role="tab" data-toggle="tab" aria-expanded="false">XML Uploads</a></li>
				<li class="p" role="presentation"><a href="#aws_files" aria-controls="aws_files" role="tab" data-toggle="tab" aria-expanded="false">AWS Files</a></li>
				<li class="t" role="presentation"><a aria-expanded="false" href="#pdf_files" aria-controls="pdf_files" role="tab" data-toggle="tab">PDF Reports</a></li>
			</ul>

			 <div class="tab-content">
			    <div role="tabpanel" class="tab-pane active" id="data_set">
					<div class="table-responsive">
					    <table class="table table-hover">
					      <thead>
					        <tr>
					          <th></th>
					          <th>Job #</th>
					          <th>Est Ship</th>
					          <th>Qty</th>
					          <th>Color</th>
					          <th>Product #</th>
					          <th>Size</th>
					          <th>Total</th>
					          <th>Front Finish</th>
					          <th>Back Finish</th>
					          <th>Custom</th>
					          <th>Binding</th>
					        </tr>
					      </thead>
					      <tbody>
					        <tr>
					          <th scope="row"><input type="checkbox"></th>
					          <td>3jf9729f</td>
					          <td>5/15/16</td>
					          <td>100</td>
					          <td>4/4</td>
					          <td>Brochures</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td></td>
					          <td></td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span><br>
					          	<b class="Label">Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span><br>
					          	<b class="Label">Binding Side</b>: <span class="Data">Left</span><br>
					          	<b class="Label">Cover Stock</b>: <span class="Data">Same As Inside</span><br>
					          	<b class="Label">Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <th scope="row"><input type="checkbox"></th>
					          <td>3jf9729f</td>
					          <td>5/15/16</td>
					          <td>100</td>
					          <td>4/4</td>
					          <td>Brochures</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td></td>
					          <td></td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span><br>
					          	<b class="Label">Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span><br>
					          	<b class="Label">Binding Side</b>: <span class="Data">Left</span><br>
					          	<b class="Label">Cover Stock</b>: <span class="Data">Same As Inside</span><br>
					          	<b class="Label">Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <th scope="row"><input type="checkbox"></th>
					          <td>3jf9729f</td>
					          <td>5/15/16</td>
					          <td>100</td>
					          <td>4/4</td>
					          <td>Brochures</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td></td>
					          <td></td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span><br>
					          	<b class="Label">Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span><br>
					          	<b class="Label">Binding Side</b>: <span class="Data">Left</span><br>
					          	<b class="Label">Cover Stock</b>: <span class="Data">Same As Inside</span><br>
					          	<b class="Label">Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <th scope="row"><input type="checkbox"></th>
					          <td>3jf9729f</td>
					          <td>5/15/16</td>
					          <td>100</td>
					          <td>4/4</td>
					          <td>Brochures</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td></td>
					          <td></td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span><br>
					          	<b class="Label">Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span><br>
					          	<b class="Label">Binding Side</b>: <span class="Data">Left</span><br>
					          	<b class="Label">Cover Stock</b>: <span class="Data">Same As Inside</span><br>
					          	<b class="Label">Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <th scope="row"><input type="checkbox"></th>
					          <td>3jf9729f</td>
					          <td>5/15/16</td>
					          <td>100</td>
					          <td>4/4</td>
					          <td>Brochures</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td></td>
					          <td></td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span><br>
					          	<b class="Label">Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span><br>
					          	<b class="Label">Binding Side</b>: <span class="Data">Left</span><br>
					          	<b class="Label">Cover Stock</b>: <span class="Data">Same As Inside</span><br>
					          	<b class="Label">Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					        <tr>
					          <th scope="row"><input type="checkbox"></th>
					          <td>3jf9729f</td>
					          <td>5/15/16</td>
					          <td>100</td>
					          <td>4/4</td>
					          <td>Brochures</td>
					          <td>8.5"x11.00"</td>
					          <td>$ 72.85</td>
					          <td></td>
					          <td></td>
					          <td>
					          	<b>Page Size</b>: <span class="Data">8.5"x5.5"</span><br>
					          	<b class="Label">Page Count</b>: <span class="Data">8 Pages (Cover+4 pages)</span><br>
					          	<b class="Label">Binding Side</b>: <span class="Data">Left</span><br>
					          	<b class="Label">Cover Stock</b>: <span class="Data">Same As Inside</span><br>
					          	<b class="Label">Binding</b>: <span class="Data">Saddle Stitching</span>
					          </td>
					        </tr>
					      
					      </tbody> </table> </div>
				</div>

			    <div id="aws_files" class="tab-pane" role="tabpanel">
			    	<h2>AWS Files</h2>
			    </div>

			    <div id="pdf_files" class="tab-pane" role="tabpanel">
			    	<h2>PDF Files</h2>
			    </div>
			    
			    <div id="xml_uploads" class="tab-pane" role="tabpanel">
			    	<h2>XML Uploads</h2>
			    </div>
			</div>
		</div>
	</div>		
</section>