<?php 
//------ VIEW - imposition-angular/index.php test 
?>


<script>
	var app =  angular.module('Imposition',[]);
 
	app.controller('myFirstController', function($scope){
 		$scope.appName = "Imposition";
 		$scope.user = "Kevin";
 		$scope.greet_user =  function(){
 
			$scope.greeting = "Hello " + $scope.user;
		};

	});
 
</script>


<h1><?php echo $heading;?></h1>
<h3><?php echo $subHeading;?></h3>

<div ng-app="Imposition"> 
	<div ng-controller="myFirstController">
    	{{"AngularJS has started..."}} </br>
    	{{"app name: " + appName}}	</br>
		{{"user: " + user}}	</br>

		<p>Name : {{user}}</p>
 
    	<input type="text" ng-model="user">
    	<button ng-click="greet_user()">Greetings</button>
 
    	<p>{{greeting}}</p>
    </div>

</div>
