<?php 
//------ VIEW - imposition-angular/index.php test 
?>

<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>

<h1><?php echo $heading;?></h1>
<h3><?php echo $subHeading;?></h3>

<div ng-app="myApp"> 
	<div ng-controller="myFirstController">
    	{{"AngularJS funziona!!!"}}
    	{{name}}		
    <div>
<script>
	var app =  angular.module('myApp',[]);
 
	app.controller('myFirstController', function($scope){
 
			$scope.name = "Coder01";
 
	});
 
</script>
</div>
