<?php 
//------ VIEW - imposition-angular/index.php test 
?>

<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>

<h1><?php echo $heading;?></h1>
<h3><?php echo $subHeading;?></h3>

<div ng-app="Imposition"> 
	<div ng-controller="myFirstController">
    	{{"AngularJS has started..."}} 
    	{{"app name: " + appName}}	
		{{"user: " + user}}	
    </div>
<script>
	var app =  angular.module('Imposition',[]);
 
	app.controller('myFirstController', function($scope){
 		$scope.appName = "Imposition";
 		$scope.user = "Kevin";
	});
 
</script>
</div>
