<h1><?php //echo $heading;?></h1>
<h3><?php //echo $subHeading;?></h3>

<div class="row">
    <div class="col-sm-3">
      <h3><button class="btn btn-xs btn-default pull-right"><i class="fa fa-info"></i></button>
          Shipping Que
      </h3>
          <div class="list-group">
  <a href="#" class="list-group-item active">
    Cras justo odio
  </a>
  <a class="list-group-item" href="#">
<h4>
  </h4>
</a>
  <a href="#" class="list-group-item">Morbi leo risus</a>
  <a href="#" class="list-group-item">Porta ac consectetur ac</a>
  <a href="#" class="list-group-item">Vestibulum at eros</a>
</div>
        
    </div>
    <div class="col-sm-6">
      <h3><button class="btn btn-xs btn-default pull-right"><i class="fa fa-info"></i></button>
          Job Info
      </h3>
      <div class="panel panel-primary">
        
        <div class="panel-body">
          Job to be shipped info
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <h3><button class="btn btn-xs btn-default pull-right"><i class="fa fa-info"></i></button>
          Shipped History
      </h3>
      <div class="panel panel-primary">
        
        <div class="panel-body">
          verbage
        </div>
      </div>
    </div>

</div>