<!--
<section>
  <div class="container">
    <h1><?php echo $heading;?></h1>
	<h3><?php echo $subHeading;?></h3>
    <hr>
  </div>
</section>
-->

<section>
    <div class="row">
		<div class="col-sm-10">
	        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
	          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
	          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
	        </div>
	        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
	          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
	          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
	        </div>
	        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
	          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
	          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
	        </div>
	        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
	          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
	          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
	        </div>
	        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
	          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
	          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
	        </div>
	        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
	          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
	          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
	        </div>
	        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
	          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
	          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
	        </div>
		</div>

		<div class="col-sm-2 text-right">
			<div style="margin:0 0 15px 0;" class="dblock">
				<a href="#" style="font-size:30px;width:100px;" class="btn btn-default"><i class="glyphicon glyphicon-search"></i>
					<div style="font-size:15px;">Search</div>
				</a>
			</div>
			<div style="margin:0 0 15px 0;" class="dblock">
				<a href="#" style="font-size:30px;width:100px;" class="btn btn-default"><i class="glyphicon glyphicon-list"></i>
					<div style="font-size:15px;">My Work</div>
				</a>
			</div>
			<div style="margin:0 0 15px 0;" class="dblock">
				<a href="#" style="font-size:30px;width:100px;" class="btn btn-default"><i class="glyphicon glyphicon-time"></i>
					<div style="font-size:15px;">Time Clock</div>
				</a>
			</div>
		</div>
    </div>
</section>

<section style="padding:100px; 0">
	<div class="container">
    <h1>Please Scan Job</h1>
  </div>
</section>





