<style>
	.dBtnWrapper a {
    width: 12.5%; 
    margin: 0px 05px 10px 0px; 
    padding: 10px 0px;
  }
  .dBtnWrapper a .icon {
    font-size:30px;
  }
  .dBtnWrapper a .count {
    font-size:25px;
    font-weight:bold
  }
  .dBtnWrapper a .count small {
    font-size:80%;
    font-weight:300;
    color:gray;
  }
</style>


<!--<section>
  <div class="container">
    <h1><?php //echo $heading;?></h1>
	<h3><?php //echo $subHeading;?></h3>
    <hr>
  </div>
</section>
-->

<section class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-2 col-sm-push-10 text-right">
			<div style="margin:0 0 15px 0;" class="dblock">
				<a href="#" style="font-size:30px;width:100px;" class="btn btn-default"><i class="glyphicon glyphicon-search"></i>
					<div style="font-size:15px;">Search</div>
				</a>
			</div>
			<div style="margin:0 0 15px 0;" class="dblock">
				<a href="#" style="font-size:30px;width:100px;" class="btn btn-default"><i class="glyphicon glyphicon-list"></i>
					<div style="font-size:15px;">My Work</div>
				</a>
			</div>
			<div style="margin:0 0 15px 0;" class="dblock">
				<a href="#" style="font-size:30px;width:100px;" class="btn btn-default"><i class="glyphicon glyphicon-time"></i>
					<div style="font-size:15px;">Time Clock</div>
				</a>
			</div>
		</div>
    
		<div class="col-xs-12 col-sm-10 col-sm-pull-2">
			<div class="row">
		        <div class="col-xs-12 dBtnWrapper">
			        <a href="#" class="btn btn-default">
			          <div class="icon"><i class="glyphicon glyphicon-duplicate"></i></div>
			          <div class="count">4 <small>(32)</small></div>
			        </a>
			        <a href="#" class="btn btn-default">
			          <div class="icon"><i class="glyphicon glyphicon-print"></i></div>
			          <div class="count">5 <small>(48)</small></div>
			        </a>
			        <a href="#" class="btn btn-default">
			          <div class="icon"><i class="glyphicon glyphicon-scissors"></i></div>
			          <div class="count">2 <small>(15)</small></div>
			        </a>
			       <a href="#" class="btn btn-default">
			          <div class="icon"><i class="glyphicon glyphicon-book"></i></div>
			          <div class="count">42</div>
			        </a>
			        <a href="#" class="btn btn-default">
			          <div class="icon"><i class="glyphicon glyphicon-plane"></i></div>
			          <div class="count">23</div>
			        </a>
			        <a href="#" class="btn btn-default">
			          <div class="icon"><i class="glyphicon glyphicon-user"></i></div>
			          <div class="count">15</div>
			        </a>
			        <a href="#" class="btn btn-default">
			          <div class="icon"><i class="glyphicon glyphicon-envelope"></i></div>
			          <div class="count">2</div>
			        </a>
		        </div>
			</div>
      
			<div class="row">
        		<div class="col-xs-12">
					<h1>Please Scan Job</h1>
				</div>
			</div>
		</div>
	</div>
</section>

