<!--
<section>
  <div class="container">
    <h1><?php echo $heading;?></h1>
	<h3><?php echo $subHeading;?></h3>
    <hr>
  </div>
</section>
-->

<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-10">
        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
        </div>
        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
        </div>
        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
        </div>
        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
        </div>
        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
        </div>
        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
        </div>
        <div class="dblock" style="display:inline-block; width:100px; margin:0 15px 15px 0; padding:10px 30px; background:lightgrey;text-align:center;">
          <div class="icon" style="font-size:30px;"><i class="glyphicon glyphicon-edit"></i></div>
          <div class="count" style="font-size:25px;font-weight:bold;">37</div>
        </div>
      </div>
    </div>
  </div>
</section>

<section style="padding:100px; 0">
	<div class="container">
    <h1>Please Scan Job</h1>
  </div>
</section>





